name: point_calculator
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod_generator: ^2.6.3
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  dio: ^5.7.0
  json_serializable: ^6.1.5
  json_annotation: ^4.9.0
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
  
